Repository upbound/nats-proxy, pull requests merged in 2022-02, with the labels that each got.

#7 Fix panic when TransportInfo is nil
  pkg/natsproxy/agent_test.go
  pkg/natsproxy/proxy.go
Labels: size/S

#8 Add Github actions for CI
  .github/workflows/backport.yml
  .github/workflows/ci.yml
  .github/workflows/commands.yml
  .github/workflows/tag.yml
Labels: size/L

#10 Update NATS to fix CVE-2022-24450
  go.mod
  go.sum
Labels: size/XS
